[project]
name = "gen-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "datasets==2.17.0",
    "evaluate==0.4.0",
    "ipython>=8.18.1",
    "peft==0.3.0",
    "rouge-score==0.1.2",
    "transformers==4.38.2",
]
